#!/usr/bin/env ruby
# frozen_string_literal: true

score = ARGV[0]
scores = score.split(',')
shots = []
scores.each do |s|
  if s == 'X'
    shots << 10
    shots << 0
  else
    shots << s.to_i
  end
end

frames = shots.each_slice(2).to_a
point = 0

frames.take(9).each.with_index(1) do |frame, index|
  subsequent_score = frames[index]
  if frame[0] == 10 && subsequent_score[0] == 10
    after_next = frames[index + 1]
    point += 20 + after_next[0]
  elsif frame[0] == 10
    point += 10 + subsequent_score.sum
  elsif frame.sum == 10
    point += 10 + subsequent_score[0]
  else
    point += frame.sum
  end
end

(9..11).each do |i|
  break if frames[i].nil?

  point += frames[i].sum
end

puts point
