#!/usr/bin/env ruby
# frozen_string_literal: true

score = ARGV[0]
scores = score.split(',')
shots = []
scores.each do |s|
  if s == 'X'
    shots << 10
    shots << 0
  else
    shots << s.to_i
  end
end

frames = shots.each_slice(2).to_a

point = frames.each.with_index.sum do |frame, index|
  subsequent_score = frames[index + 1]
  if index >= 9
    frames[index].sum
  elsif frame[0] == 10 && subsequent_score[0] == 10
    after_next = frames[index + 2]
    20 + after_next[0]
  elsif frame[0] == 10
    10 + subsequent_score.sum
  elsif frame.sum == 10
    10 + subsequent_score[0]
  else
    frame.sum
  end
end

puts point
