#!/usr/bin/env ruby
# frozen_string_literal: true

score = ARGV[0]
scores = score.split(',')
shots = []
scores.each do |s|
  if s == 'X'
    shots << 10
    shots << 0
  else
    shots << s.to_i
  end
end

frames = []
shots.each_slice(2) do |s|
  frames << s
end

point = 0
times = 1
under_tenth = frames.take(9)

under_tenth.each do |frame|
  subsequent_score = frames[times]
  if frame[0] == 10 && subsequent_score[0] == 10
    after_next = frames[times + 1]
    point += 20 + after_next[0]
  elsif frame[0] == 10
    point += 10 + subsequent_score.sum
  elsif frame.sum == 10
    point += 10 + subsequent_score[0]
  else
    point += frame.sum
  end
  times += 1
end

(9..11).each do |i|
  break if frames[i].nil?

  point += frames[i].sum
end

puts point
